name:                dl-first-principle-tutorial
version:             0.1.0.0
github:              "githubuser/dl-first-principle-tutorial"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dl-first-principle-tutorial#readme>

dependencies:
- base >= 4.7 && < 5
- ad
- adjunctions
- attoparsec
- attoparsec-binary
- backprop
- bitvec
- bytestring
- cassava
- deepseq
- diagrams-core
- diagrams-lib
- diagrams-rasterific
- diagrams-svg
- directory
- distributive
- dlist
- equational-reasoning
- filepath
- foldl
- generic-data
- generic-lens
- ghc-typelits-knownnat
- ghc-typelits-presburger
- heaps
- hybrid-vectors
- lens
- linear
- massiv
- massiv-io
- massiv-persist
- matrix
- mwc-random
- persist
- random
- reflection
- resourcet
- semigroupoids
- sized
- split
- streaming
- streaming-attoparsec
- streaming-bytestring
- strict
- subcategories
- these
- transformers
- type-natural
- unliftio
- vector
- vector-th-unbox

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fsimpl-tick-factor=1000

library:
  source-dirs: src

executables:
  iris:
    main:         Main.hs
    source-dirs:  app/iris
    ghc-options:
    - -O2
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative

  circles:
    main:         Main.hs
    source-dirs:  app/circles
    ghc-options:
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative
    - time

  spirals-batchnorm:
    main:         Main.hs
    source-dirs:  app/spirals-batchnorm
    ghc-options:
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative
    - time

  mnist:
    main:         Main.hs
    source-dirs:  app/mnist
    ghc-options:
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative
    - time
