name:                dl-first-principle-tutorial
version:             0.1.0.0
github:              "githubuser/dl-first-principle-tutorial"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dl-first-principle-tutorial#readme>

dependencies:
- base >= 4.7 && < 5
- ad
- adjunctions
- backprop
- bitvec
- bytestring
- cassava
- deepseq
- diagrams-core
- diagrams-lib
- diagrams-rasterific
- diagrams-svg
- directory
- distributive
- dlist
- filepath
- generic-lens
- generic-data
- lens
- linear
- massiv
- matrix
- massiv-io
- split
- strict
- random
- mwc-random
- reflection
- vector
- vector-th-unbox
- foldl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  iris:
    main:         Main.hs
    source-dirs:  app/iris
    ghc-options:
    - -O2
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative
  circles:
    main:         Main.hs
    source-dirs:  app/circles
    ghc-options:
    - -O2
    dependencies: 
    - dl-first-principle-tutorial
    - optparse-applicative
