name:                mnist-core
version:             0.1.0.0
github:              "githubuser/mnist-core"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mnist-core#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- attoparsec-binary
- attoparsec
- deepseq
- streaming
- streaming-bytestring
- streaming-attoparsec
- bytestring
- massiv
- massiv-io
- vector
- vector-th-unbox

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
